### ISSUE TITLE
Compatibility to Codeigniter 3.0 RC2?

### ISSUE THREAD

**Issue by JohnSmith37** [sjlu/CodeIgniter-Bootstrap#33]
New to CI and I was wondering if this package would be compatible with the version 3.0 RC2?

**Comment by sjlu** [comment]
Yes, there is a process to it though. You should definitely read over the release notes and upgrade notes to see the changes.




I'll personally do the update once it's out of RC

**Comment by JohnSmith37** [comment]
Thanks for the quick response, I'll give it a try



A bit out of scope, but between CI and Laravel, which one would you recommend for a PHP framework beginner?

**Comment by sjlu** [comment]
So IMHO, CI is super basic, probably the fastest one I was able to learn. Laravel has a lot better structure and maintainability.




Small projects I use CI, Laravel for longer term ones. But this is just from preference.

**Comment by sjlu** [comment]
See #36, upgraded to 3.0
