### ISSUE TITLE
After installing, attempting to load the Welcome controller gives an error.

### ISSUE THREAD

**Issue by elsewares** [sjlu/CodeIgniter-Bootstrap#37]
For some reason, the function base_url() isn't available in the header view, and throws an error - not sure if this is an issue with .htaccess, but I wasn't able to track down the problem quickly. Might be worth a look.

**Comment by sjlu** [comment]
Ah yes. It's cause I did not auto load the "url" helper in the config. Will fix this today.

**Comment by sjlu** [comment]
Fixed!
