### ISSUE TITLE
Returned an error at the end of make

### ISSUE THREAD

**Issue by marcelod** [sjlu/CodeIgniter-Bootstrap#40]
Hello, I cloned the project and run the make. 
In the end I got the message 
> sed: -e expression #1, character 1: Unknown command: `.'
> make: ** [run] Erro 1

Apparently it's all right.

I am using : Linux mynote 3.13.0-51-generic #84-Ubuntu SMP Wed Apr 15 12:08:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sjlu** [comment]
sed works differently out of the box on Linux than it does macs. I'll resolve this by replacing it with a file copy instead.

**Comment by sjlu** [comment]
Done.
